In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler,LabelEncoder, OneHotEncoder
import pickle
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [2]:
data=pd.read_csv("Churn_Modelling.csv")
data.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [3]:
#Process the data
data=data.drop(['RowNumber','CustomerId','Surname'],axis=1)

In [4]:
label_encoder_gender = LabelEncoder()
data['Gender'] = label_encoder_gender.fit_transform(data['Gender'])

In [5]:
onehot_encoder_geo = OneHotEncoder(handle_unknown='ignore')
geo_encoded = onehot_encoder_geo.fit_transform(data[['Geography']]).toarray()
geo_encoded_df = pd.DataFrame(geo_encoded, columns=onehot_encoder_geo.get_feature_names_out(['Geography']))
geo_encoded_df.head()

   Geography_France  Geography_Germany  Geography_Spain
0               1.0                0.0              0.0
1               0.0                0.0              1.0
2               1.0                0.0              0.0
3               1.0                0.0              0.0
4               0.0                0.0              1.0

In [6]:
data=pd.concat([data.drop(columns=['Geography'], errors='ignore'), geo_encoded_df], axis=1)
data.head()

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain
0,619,0,42,2,0.00,1,1,1,101348.88,1,1.0,0.0,0.0
1,608,0,41,1,83807.86,1,0,1,112542.58,0,0.0,0.0,1.0
2,502,0,42,8,159660.80,3,1,0,113931.57,1,1.0,0.0,0.0
3,699,0,39,1,0.00,2,0,0,93826.63,0,1.0,0.0,0.0
4,850,0,43,2,125510.82,1,1,1,79084.10,0,0.0,0.0,1.0

In [7]:
# split the data into features and target variable
x = data.drop('EstimatedSalary', axis=1)
y = data['EstimatedSalary']

In [8]:
## split the data in training and testing sets
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [9]:
scaler=StandardScaler()
x_train=scaler.fit_transform(x_train)
x_test=scaler.transform(x_test)

In [10]:
# Save the encoder and scaler for later use
with open('label_encoder.pkl', 'wb') as f:
    pickle.dump(label_encoder_gender, f)
with open('onehot_encoder_geo.pkl', 'wb') as f:
    pickle.dump(onehot_encoder_geo, f)
with open('scaler.pkl', 'wb') as f:
    pickle.dump(scaler, f)

In [11]:
#Build the model
model = Sequential([
    Dense(64, activation='relu', input_shape=(x_train.shape[1],)),
    Dense(32, activation='relu'),
    Dense(1)  # Output layer for regression
])

# Compile model
model.compile(optimizer='adam', loss='mean_absolute_error', metrics=['mean_absolute_error'])
model.summary()

D:\Workspace\GenAI\.venv\Lib\site-packages\keras\src\layers\core\dense.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 64)             │           832 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 2,945 (11.50 KB)

 Trainable params: 2,945 (11.50 KB)

 Non-trainable params: 0 (0.00 B)

In [12]:
from tensorflow.keras.callbacks import EarlyStopping, TensorBoard
import datetime

#set up TensorBoard callback
log_dir = "regressionlogs/fit/" + datetime.datetime.now().strftime("%Y%m%d-%H%M%S")
tensorboard_callback = TensorBoard(log_dir=log_dir, histogram_freq=1)

In [13]:
#Set up earlystopping
early_stopping_callback = EarlyStopping(monitor='val_loss', patience=5, restore_best_weights=True)

In [14]:
#train the model
hisory = model.fit(
    x_train, y_train,
    validation_data=(x_test, y_test),
    epochs=100,
    callbacks=[tensorboard_callback,early_stopping_callback],
)

Epoch 1/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 100376.0000 - mean_absolute_error: 100376.0000 - val_loss: 98507.0703 - val_mean_absolute_error: 98507.0703
Epoch 2/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 99573.2500 - mean_absolute_error: 99573.2500 - val_loss: 96870.9141 - val_mean_absolute_error: 96870.9141
Epoch 3/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 96680.9688 - mean_absolute_error: 96680.9688 - val_loss: 92592.5156 - val_mean_absolute_error: 92592.5156
Epoch 4/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 90947.7734 - mean_absolute_error: 90947.7734 - val_loss: 85460.4766 - val_mean_absolute_error: 85460.4766
Epoch 5/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 82650.0000 - mean_absolute_error: 82650.0000 - val_loss: 76385.3438 - val_mean_absolute_error: 76385.3438
Epoch 6/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 73101.5469 - mean_absolute_error: 73101.5469 - val_loss: 67236.9766 - val_mean_absolute_error: 67236.9766
Epoch 7/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 64136.3359 - mean_absolute_error: 64136.3359 - val_loss: 59537.8516 - val_mean_absolute_error: 59537.8516
Epoch 8/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 57300.1445 - mean_absolute_error: 57300.1445 - val_loss: 54435.7930 - val_mean_absolute_error: 54435.7930
Epoch 9/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 53186.3281 - mean_absolute_error: 53186.3281 - val_loss: 51730.3086 - val_mean_absolute_error: 51730.3086
Epoch 10/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 51201.7617 - mean_absolute_error: 51201.7617 - val_loss: 50795.0742 - val_mean_absolute_error: 50795.0742
Epoch 11/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 50432.3008 - mean_absolute_error: 50432.3008 - val_loss: 50540.6289 - val_mean_absolute_error: 50540.6289
Epoch 12/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 50170.9961 - mean_absolute_error: 50170.9961 - val_loss: 50481.8047 - val_mean_absolute_error: 50481.8047
Epoch 13/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 50079.9297 - mean_absolute_error: 50079.9297 - val_loss: 50455.9414 - val_mean_absolute_error: 50455.9414
Epoch 14/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 50021.7461 - mean_absolute_error: 50021.7461 - val_loss: 50434.2344 - val_mean_absolute_error: 50434.2344
Epoch 15/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 49973.8633 - mean_absolute_error: 49973.8633 - val_loss: 50411.0039 - val_mean_absolute_error: 50411.0039
Epoch 16/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 49936.4727 - mean_absolute_error: 49936.4727 - val_loss: 50404.4258 - val_mean_absolute_error: 50404.4258
Epoch 17/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 49903.8516 - mean_absolute_error: 49903.8516 - val_loss: 50393.1055 - val_mean_absolute_error: 50393.1055
Epoch 18/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 49875.2578 - mean_absolute_error: 49875.2578 - val_loss: 50390.5273 - val_mean_absolute_error: 50390.5273
Epoch 19/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 49848.5273 - mean_absolute_error: 49848.5273 - val_loss: 50381.3047 - val_mean_absolute_error: 50381.3047
Epoch 20/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 49823.0000 - mean_absolute_error: 49823.0000 - val_loss: 50374.8203 - val_mean_absolute_error: 50374.8203
Epoch 21/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 49802.6406 - mean_absolute_error: 49802.6406 - val_loss: 50373.1953 - val_mean_absolute_error: 50373.1953
Epoch 22/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 49778.8789 - mean_absolute_error: 49778.8789 - val_loss: 50365.4258 - val_mean_absolute_error: 50365.4258
Epoch 23/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 49760.9805 - mean_absolute_error: 49760.9805 - val_loss: 50354.0469 - val_mean_absolute_error: 50354.0469
Epoch 24/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 49742.3438 - mean_absolute_error: 49742.3438 - val_loss: 50342.4727 - val_mean_absolute_error: 50342.4727
Epoch 25/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 49723.5625 - mean_absolute_error: 49723.5625 - val_loss: 50339.9141 - val_mean_absolute_error: 50339.9141
Epoch 26/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 49703.7227 - mean_absolute_error: 49703.7227 - val_loss: 50334.1992 - val_mean_absolute_error: 50334.1992
Epoch 27/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 49689.7422 - mean_absolute_error: 49689.7422 - val_loss: 50329.4336 - val_mean_absolute_error: 50329.4336
Epoch 28/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 49675.0703 - mean_absolute_error: 49675.0703 - val_loss: 50325.3867 - val_mean_absolute_error: 50325.3867
Epoch 29/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 49658.9844 - mean_absolute_error: 49658.9844 - val_loss: 50313.2578 - val_mean_absolute_error: 50313.2578
Epoch 30/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 49645.7461 - mean_absolute_error: 49645.7461 - val_loss: 50321.2578 - val_mean_absolute_error: 50321.2578
Epoch 31/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 49631.1719 - mean_absolute_error: 49631.1719 - val_loss: 50325.8555 - val_mean_absolute_error: 50325.8555
Epoch 32/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 49620.8867 - mean_absolute_error: 49620.8867 - val_loss: 50327.0703 - val_mean_absolute_error: 50327.0703
Epoch 33/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 49611.6523 - mean_absolute_error: 49611.6523 - val_loss: 50325.6953 - val_mean_absolute_error: 50325.6953
Epoch 34/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 49600.1836 - mean_absolute_error: 49600.1836 - val_loss: 50330.1562 - val_mean_absolute_error: 50330.1562

In [15]:
%load_ext tensorboard

In [16]:
import sys
print(sys.executable)
import os
os.environ["TENSORBOARD_BINARY"] = r"D:\Workspace\GenAI\.venv\Scripts\tensorboard.exe"
import os
print(os.path.exists(r"D:\Workspace\GenAI\.venv\Scripts\tensorboard.exe"))

D:\Workspace\GenAI\.venv\Scripts\python.exe
True

In [17]:
# %tensorboard --logdir regressionlogs/fit
# %tensorboard --logdir regressionlogs --host 127.0.0.1
%tensorboard --logdir regressionlogs/fit --port 6007

In [18]:
#Evaluate the model on the test data
test_loss, test_mae= model.evaluate(x_test, y_test)
print(f'Test MAE: {test_mae}')

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 845us/step - loss: 50313.2578 - mean_absolute_error: 50313.2578
Test MAE: 50313.2578125

In [ ]:
model.save('regression_model.h5')